FROM ruby:2.7.5-alpine AS base
RUN apk add --update --no-cache \
  postgresql-dev \
  tzdata \
  nodejs \
  yarn

FROM base AS dependencies
RUN apk add --update --no-cache build-base cmake \
  && rm -rf /var/cache/apt/* 
COPY Gemfile Gemfile.lock CommonGemfile NextGemfile NextGemfile.lock ./
RUN bundle install --jobs=3 --retry=3

FROM base
RUN adduser -D app
USER app
WORKDIR /home/app
COPY --from=dependencies /usr/local/bundle/ /usr/local/bundle/
COPY --chown=app . /home/app
CMD bundle exeec swarm:migrate && bundle exec rails s -p 3000 -b 0.0.0.0 
