ARG RUBY_VERSION

FROM ruby:$RUBY_VERSION

# The below list of arguments needs to be positionned after the FROM
# statement, if not they will be ignored and docker build will fail.
ARG PG_CLI_VERSION
ARG BUNDLER_VERSION

LABEL version="1.0.0"

RUN apt-get update -qq \
  && apt-get install -y postgresql-client=${PG_CLI_VERSION} --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3 \
  BUNDLE_PATH=/opt/gems \
  GEM_PATH=/opt/gems \
  GEM_HOME=/opt/gems \
  BUNDLE_GEMFILE=NextGemfile

WORKDIR /opt/workbook

COPY CommonGemfile NextGemfile NextGemfile.lock /opt/workbook/

COPY entrypoints/* /usr/local/bin/

RUN chmod -R 755 /usr/local/bin/entrypoint-next.sh

RUN echo "gem: --no-ri --no-rdoc --no-document" > ~/.gemrc \
    && gem install bundler:${BUNDLER_VERSION} \
    && bundle install --verbose \
    && gem cleanup all

COPY . /opt/worbook/

EXPOSE 3000

CMD ["entrypoint-next.sh"]
