openapi: "3.0.0"
info:
  description: Workbook open source platform
  version: "1.0.0"
  title: "Worbook"
  license:
    name: "GPL 3.0"
    url: ""
  termsOfService: "https://wbk.so-gineers.com"
  contact:
    email: "workbook@so-gineers.com"
servers:
  - url: "https://workbook-api-demo.herokuapp.com"
    description: "heroku"
  - url: "http://localhost:3312"
    description: "local"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Api key auth
      in: header
tags:
  - name: teachers
    description: Endpoints for teachers
paths:
  /teachers/sessions:
    $ref: "./paths/teachers/sessions.yml"
