AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - db/migrate/*
    - db/old-migrate/*
    - app/old-controllers/*


Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - lib/app/teachers/tokens/encoder.rb
    - lib/app/exceptions/api_error.rb

Metrics/AbcSize:
  Exclude:
    - app/controllers/concerns/global_request_logging.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 20

Style/Documentation:
  Enabled: false 

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
