version: '3.9'
services:
  base_api_alpine: &base_api_alpine_config
    build:
      dockerfile: docker/dev/Dockerfile.alpine
      context: .
      args:
        RUBY_VERSION: '2.7'
        PG_CLI_VERSION: '13+225'
        BUNDLER_VERSION: '2.3.7'
        BUNDLE_GEMFILE: Gemfile
    command: sh -c "bundle exec rails db:create swarm:migrate && bundle exec guard --force-polling"
    env_file: ./docker/dev/dev.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wbk-api-net
      - wbk-db-net
    volumes:
      - ./:/home/app
  api_ruby_alpine_tests:
    <<: *base_api_alpine_config
    env_file: ./docker/dev/test.env
  api_ruby_alpine:
    <<: *base_api_alpine_config

  base_api: &base_api_config
    build:
      dockerfile: docker/dev/Dockerfile
      context: .
      args:
        RUBY_VERSION: '2.7'
        PG_CLI_VERSION: '13+225'
        BUNDLER_VERSION: '2.3.7'
    env_file: ./docker/dev/dev.env
    image: base_api
    networks:
      - wbk-api-net
      - wbk-db-net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/opt/workbook/
      - ./tmp:/opt/workbook/tmp/
  api_ruby:
    <<: *base_api_config
    container_name: wbk_api_ruby 
    ports:
      - '4110:3000'
    command: |
      bundle exec rails swarm:migrate && bundle exec rails s -b 0.0.0.0
  api_ruby_tests:
    <<: *base_api_config
    ports:
      - '4111:3000'
    env_file: ./docker/dev/test.env
    command: |
      bundle exec rails swarm:migrate && bundle exec guard
  db_backups:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.backup
      args:
        PG_CLI_VERSION: '14'
    depends_on:
      db:
        condition: service_healthy
    env_file: ./docker/dev/dev.env
    networks:
      - wbk-db-net
    stdin_open: true
    tty: true
    volumes:
      - database_backups_v:/var/backups
      - database_backups_l:/var/log/cron
  db:
    image: postgres:14
    container_name: wbk_postgres_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432'
    networks:
      - wbk-db-net
    environment:
      - POSTGRES_DB=workbooker_api_development
      - POSTGRES_USER=xaragne
      - POSTGRES_PASSWORD=xaragne
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "xaragne"]
      interval: 10s
      timeout: 5s
      retries: 5
  swagger_ui_teachers:
    build:
      context: ./swagger/teachers
    environment:
      SWAGGER_FILE: /swagger.yml
    volumes:
      - ./swagger/teachers/api.yml:/swagger.yml
      - ./swagger/teachers/paths:/paths
    ports:
      - "3518:8080"
  # Swagger editor for teachers
  # Visit http://localhost:3517 to see it working
  swagger_editor_teachers:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /swagger.yml
    volumes:
      - ./swagger/teachers/api.yml:/swagger.yml
      - ./swagger/teachers/paths:/paths
    ports:
      - "3517:8080"
  # Swagger editor for students
  # Visit http://localhost:3516 to see it working
  swagger_editor_students:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /swagger.yml
    volumes:
      - ./swagger/students/api.yml:/swagger.yml
      - ./swagger/students/paths:/paths
    ports:
      - "3516:8080"
networks:
  wbk-api-net:
    name: workbook-api-network
  wbk-db-net:
    name: workbook-db-network
volumes:
  db: {}
  gems: {}
  database_backups_v: {}
  database_backups_l: {}

