name: Deploy
on:
  push:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        env:
          RUBY_VERSION: 2.7
          PG_CLI_VERSION: 13+225
          BUNDLER_VERSION: 2.2.31
          BUNDLE_GEMFILE: Gemfile
          # The variables prefixed by hd are sent to running app on heroku
          HD_RAILS_SECRET_KEY: notasecretbutwearejusttesting
          HD_RAILS_ENV: heroku
          HD_RAILS_DB_NAME: workbook_api_production
          SENTRY_DSN: ${{secrets.SENTRY_DSN_HEROKU}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "workbook-api-demo"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          dontuseforce: true
          stack: "container"
          docker_build_args: |
            RUBY_VERSION
            PG_CLI_VERSION
            BUNDLER_VERSION
            BUNDLE_GEMFILE
